ALL: child_process.out parent_process.out

parent_process.out: parent_process.c
	gcc -g -Wall parent_process.c -o parent_process.out

child_process.out: child_process.c
	gcc -g -Wall child_process.c -o child_process.out
